### PR TITLE
Issue 246 Updated Asset Links in EDDE

### LINKED ISSUE #246: Update `assets` links in EDDE
All links under `https://www.nyc.gov/assets/planning/` will stop working with the launch of the new agency website. All of those links are documented and categorized in this [spreadsheet](https://nyco365-my.sharepoint.com/:x:/g/personal/hrosa_planning_nyc_gov/EZml4t7PSIxHt2v3x8Py9XQB4s-rGdEEoepbIbP74N1npA?e=9sfDxw). The web team has copied all of these files under `https://s-media.nyc.gov/agencies/dcp/assets/files/AE` in the root directory. All file name should be the same except changed to dash-case  ~(note exception for `econ_2016acs5yr_puma.xlsx`)~ (edit: file name kebab-cased by Mary on 3/26/2025).

Image

### PR DESCRIPTION
**Pull request by horatiorosa**
#### Tasks/Bug Numbers
 - Closes #246

### CODE REVIEW

File: src/pages/about.tsx [hunk 1]
```diff
@@ -149,7 +149,7 @@ const AboutPage = () => {
             <Text pb="0.5em">
               As of June 1, 2022,{" "}
               <Link
-                href="https://www1.nyc.gov//assets/planning/download/pdf/data-maps/edde/racial-equity-report-applicability-chart.pdf"
+                href="https://s-media.nyc.gov/agencies/dcp/assets/files/AE/racial-equity-report-applicability-chart.pdf"
```
Comment (horatiorosa) [inline src/pages/about.tsx:152]: Redirect fails, no asset found

Comment (horatiorosa) [reply src/pages/about.tsx:152]: Asset link created by WebTeam 3/26/2025

**Review by TangoYankee — APPROVED** [review]
The updated links are functional. I am trusting that we're not missing other links that also need to be changed.
